version: '3.8'

services:
  transactions-storage:
    image: postgres:latest
    container_name: transactions-storage
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - transactions-storage
      - flyway
    environment:
      DB_URL: ${JDBC_URL}://transactions-storage:${DB_PORT}/${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DELAY: ${DELAY}
      PUBLIC_NODE_URL: ${PUBLIC_NODE_URL}
      PUBLIC_NODE_KEY: ${PUBLIC_NODE_KEY}

  flyway:
    image: flyway/flyway
    command: -url=${JDBC_URL}://transactions-storage:${DB_PORT}/${DB_NAME} -schemas=public -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate
    depends_on:
      - transactions-storage
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql